services:
    open-webui:
        image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
        container_name: open-webui
        privileged: true
        volumes:
            - open-webui:/app/backend/data
        ports:
            - ${OPEN_WEBUI_PORT-3009}:8080
        environment:
            - OPENAI_API_BASE_URL=http://host.docker.internal:9099
            - OPENAI_API_KEY=0p3n-w3bu!
        extra_hosts:
            - host.docker.internal:host-gateway
        restart: unless-stopped

    pipelines:
        build:
            context: .
            dockerfile: Dockerfile
        develop:
            watch:
                - action: sync
                  path: ./utils
                  target: /app/utils
                - action: rebuild
                  path: main.py
                - action: rebuild
                  path: start.sh
        container_name: pipelines
        ports:
            - 9099:9099
        env_file:
            - .env
        volumes:
            - ./pipelines:/app/pipelines
        environment:
            - PIPELINES_URLS=https://github.com/jedwards1230/lilbro-pipelines;
        extra_hosts:
            - host.docker.internal:host-gateway
        restart: unless-stopped

volumes:
    open-webui: {}
