name: Create and publish Docker images with specific build args

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - dev

env:
    REGISTRY: ghcr.io
    FULL_IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
    build-main-image:
        uses: ./.github/workflows/build-docker-image.yaml
        with:
            image_name: ${{ github.repository }}
            cache_id: main

    build-cuda-image:
        uses: ./.github/workflows/build-docker-image.yaml
        if: false
        with:
            image_name: ${{ github.repository }}
            image_tag: |
                type=raw,enable=${{ github.ref == 'refs/heads/main' }},prefix=,suffix=,value=cuda
            cache_id: cuda
            extract_flavor: suffix=-cuda,onlatest=true
            build_args: |
                USE_CUDA=true

    merge-main-images:
        uses: ./.github/workflows/merge-docker-images.yaml
        needs: [build-main-image]
        with:
            cache_id: main

    merge-cuda-images:
        uses: ./.github/workflows/merge-docker-images.yaml
        needs: [build-cuda-image]
        with:
            cache_id: cuda
            extract_flavor: suffix=-cuda,onlatest=true
            extract_tags: |
                type=raw,enable=${{ github.ref == 'refs/heads/main' }},prefix=,suffix=,value=cuda
